name: Update deps

on:
  # schedule:
  #   # weekly run as example (CRON in UTC)
  #   - cron: '0 21 * * *'
  push: 
    branches:
      - main

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run update script
        run: |
          chmod +x scripts/ci/update-cdn-exports.sh
          scripts/ci/update-cdn-exports.sh

      - name: Create Pull Request if files changed
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: detect new dependencies"
          branch: "update-dependencies-${{ github.run_id }}"
          title: "chore: update dependencies"
          body: |
            This PR was created because new versions have been detected.
